kind = "web"
previewPath = "/"
title = "NUASA"
version = "1.0.0"
id = "artifacts/nuasa"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21844

[services.development]
run = "pnpm --filter @workspace/nuasa run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nuasa", "run", "build" ]
publicDir = "artifacts/nuasa/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21844"
BASE_PATH = "/"
